### ISSUE TITLE
help needed with code please 

### ISSUE THREAD

**Issue by StrangerPy** [joebowen/landing_zone_project#1]
Hi , 

I had a go at this and ran into problems .... 

Im getting errors when trying to run the code ....
errors like 
orp.startup.Application.setLogOutputLevel(log_level)
AttributeError: type object 'net.sf.openrocket.startup.Application' has no attribute 'setLogOutputLevel'

I also had to change the Startup to SwingStartup ...but still having issues on all examples ....

Would you be so kind as to make the examples work with latest version of OpenRocket ?
As I think the classes have changed in the latest version ...

Or could you point me to the correct version of OpenRocket to use with the landing zone project...

Thanks 

:)

**Comment by joebowen** [comment]
It's great to see someone take an interest in one of my projects, unfortunately you're running into the same issues that I had when I tried to create this.  You're correct that all the classes have changed and I'm not familiar enough with the OpenRocket project enough to figure out what's changed.  I'd be happy to lend some assistance, if I can, but you've basically reached the same road block I did.

Joe  :-)

**Comment by joebowen** [comment]
Just fyi, most of this code started here http://wiki.openrocket.info/Scripting_with_Python_and_JPype The real challenge is going to be updating the file orhelper.py and it's supporting usage to work with the current version of OpenRocket.

Looking at their versions on (sourceforge)[http://sourceforge.net/projects/openrocket/files/openrocket/] and the quote in the wiki ("> 1.19."... which might be 1.1.9).  You might be able to get this software working with version 12.03.

Let me know what you find.  I'd still be interested in using this tool and developing it into a more field ready tool that I can use at my launch site.

**Comment by StrangerPy** [comment]
Hmmmm i see ....

Ok ill try and use the codes u have listed with Openrocket 12.03 and see what happens ...
Its ashame nobody has kept this up to date as it would be interesting to use ...

Im too much of newbie to be able to modify much ....

anyways thanks for response

**Comment by joebowen** [comment]
@StrangerPy Any luck with 12.03?  I've been thinking of reworking the code but I'd have to get someone that's more familiar with the current OpenRocket code base to point me in the right direction to find the correct functions to hook into.

**Comment by StrangerPy** [comment]
yea tried it same issues as you really....
I think too many changes and the whole thing would need to be redone :( 
Im still learning python basics and no nothing on java :)

**Comment by StrangerPy** [comment]
BTW if u do ever get this going update this area

**Comment by joebowen** [comment]
Will do. You as well. It's too bad we can't get someone who's more up to
date on the current openrocket to go over how the code base has changed
since this base script was developed.  I could probably figure out the
python side if I could figure out the open rocket code base.
